version: '2'

services:
  lava-server:
    container_name: lava-server
    hostname: lava-server
    build:
      context: ./
      args:
        # Version of lavasoftware/lava-server base container
        version: 2022.11
        # Administator username
        admin_username: "admin"
        # Administator password
        admin_password: "password"
        # Administator email
        admin_email: "admin@localhost.com"
        # Administrator token if any (e.g. "d0siRzClNHWNtUYJbpmjOPEyPp0QLCKqQtDGTftN")
        admin_token: ""
        # List of Available workers by hostname
        workers: "worker0"
        # List of additional packages to install (e.g. "vim gcc")
        extra_packages: "net-tools"
    restart: always
    ports: # Ports exposed to outside world (host-port:container-port)
      - "5580:80"  # http for web interface
      - "5555:5555"  # logger socket
      - "5556:5556"  # master socket
    volumes: # overlays to apply on top of lavasoftware container
      # Custom startup scripts
      - ./overlays/root/entrypoint.d:/root/entrypoint.d
      # Device dictionnaries
      - ./overlays/etc/lava-server/dispatcher-config/devices:/etc/lava-server/dispatcher-config/devices
      # Lava settings
      - ./overlays/etc/lava-server/settings.conf:/etc/lava-server/settings.conf
      - ./overlays/etc/lava-server/settings.d/01-autoregister.yaml:/etc/lava-server/settings.d/01-autoregister.yaml
